version: "3.9"

services:
  angular-frontend:
    build:
      context: ./mustaqil-frontend
      dockerfile: Dockerfile.prod
    ports:
      - "4200:80"
    networks:
      - app-network

  mustaqeel-admin:
    build:
      context: ./mustaqeel-admin
      dockerfile: Dockerfile.prod
    ports:
      - "5000:80"
    networks:
      - app-network

  laravel-backend:
    build:
      context: ./mustaqeel-api
      dockerfile: Dockerfile
    container_name: laravel-backend
    depends_on:
      - mysql-db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: mustaqel_v2
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - app-network

  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    depends_on:
      - laravel-backend
    volumes:
      - ./mustaqeel-api:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9000:80"
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mustaqel_v2
    ports:
      - "3306:3306"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
