version: "3.9"

services:
  mustaqeel-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mustaqeel-backend
    depends_on:
      - mysql-db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: mustaqel_v2
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - laravel-network

  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    depends_on:
      - mustaqeel-backend
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8069:80"
    networks:
      - laravel-network

  mysql-db:
    image: mysql:8.0
    container_name: mustaqeel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mustaqel_v2
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8070:8080"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data:
